<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC632LBb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC632LBb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC632LBb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC632LBb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC632LBb\App_KernelDevDebugContainer([
    'container.build_hash' => 'C632LBb',
    'container.build_id' => '8255dcab',
    'container.build_time' => 1705935472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC632LBb');
