<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2B5fPN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2B5fPN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2B5fPN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2B5fPN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF2B5fPN\App_KernelDevDebugContainer([
    'container.build_hash' => 'F2B5fPN',
    'container.build_id' => '1921ae87',
    'container.build_time' => 1706471457,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2B5fPN');
